export const LOGIN = 'LOGIN'
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const LOAD_PROVIDERS = 'LOAD_PROVIDERS'
export const LOAD_CONSUMERS = 'LOAD_CONSUMERS'
export const LOAD_USER = 'LOAD_USER'
